### ISSUE TITLE
Handling standard out on windows is failing

### ISSUE THREAD

**Issue by FlorianRupp** [pystage/pystage#10]
Handling standard out on windows is not that easy as on Linux ;) Due to this issue, any PyStage code execution is not possible atm.

So far, I found the documentation of the windows StdHandle here: https://docs.microsoft.com/en-us/windows/console/getstdhandle. Thus the Codes are:
* Output: -11
* Error: -12

Nevertheless, the following exception is yielded:

```OSError: exception: access violation reading 0x0000000000000024```

**Comment by kaiec** [comment]
This is related to #6 . For now we should just not do redirections and rather see that we keep the SVG imports to a minimum for standard examples, i.e., we deliver all our images additionally as PNG and the converter creates pngs during import.

**Comment by kaiec** [comment]
As SVG import seems to work now in pygame / SDL, I consider this done.
