### ISSUE TITLE
NameError: name 'self' is not defined

### ISSUE THREAD

**Issue by ghost** [pystage/pystage#106]
I keep getting this error many times...
Traceback (most recent call last):
  File "G:\My Drive\Documents\Pycharm\Goup\main.py", line 24, in <module>
    self.when_timer_GREATERTHAN(0.1)
    ^^^^
NameError: name 'self' is not defined

**Comment by kaiec** [comment]
This is not enough information to understand the problem. If this is still relevant, please provide an SB3 file (if this is a conversion). You can use the online converter to submit a URL showing the SB3 File and the generated Python code: https://convert.pystage.org/

If you directly program in Python, then this is probably a bug in your code, feel free to join our discord and ask for help.
