### ISSUE TITLE
Error says can;t find file

### ISSUE THREAD

**Issue by RublogDev** [pystage/pystage#107]
I typed:
python -m pystage.convert.sb3 casg.sb3 -l en -d Downloads
and I get an error "FileNotFoundError: [Errno 2] No such file or directory: 'casg'" I need help because I don't know how to fix that erroe I tried everything.

**Comment by loyaniu** [comment]
Make sure you are in the correct directory where the `casg.sb3` file is located, or provide the full path to the file.

Like this: 

`python -m pystage.convert.sb3 /full/path/to/casg.sb3 -l en -d Downloads`
