### ISSUE TITLE
Missing block: Change Effect To

### ISSUE THREAD

**Issue by raspberrypieman** [pystage/pystage#111]
Hi, I was thinking about trying to make a Scratch to Python converter, when I came across your project, and I am very impressed - good job. As you say this is a "pre alpha version" and expect a few issues. 
I am keen to see this working, so I tried with the simple "Greetings Card" project, which can be downloaded from here: https://scratch.mit.edu/projects/11806234/editor/

I am running on Windows/10 using Python 3.9.1
I first saved the project as "Greeting_Card.sb3", then
converted it using: python -m pystage.convert.sb3 Greeting_Card.sb3 -l en -d converted
I got these messages during conversion:

Creating project: greeting_card
Exporting to: converted
No API method for sensing_touchingobjectmenu
No API method for sensing_touchingobjectmenu
No API method for looks_changeeffectby
No API method for looks_changeeffectby

A DIR /s  of the converted directory reveals:
25/03/2024  14:35             2,961 greeting_card.py
25/03/2024  14:30    <DIR>          images
25/03/2024  14:30    <DIR>          sounds
               1 File(s)          2,961 bytes

 Directory of ...\converted\images

25/03/2024  14:30             1,381 arrow1.svg
25/03/2024  14:30             1,454 arrow2.svg
25/03/2024  14:30             6,125 backdrop1.svg
25/03/2024  14:30             6,299 backdrop2.svg
25/03/2024  14:30             6,303 backdrop3.svg
25/03/2024  14:30               740 birthday1.svg
25/03/2024  14:30            30,698 cake.svg
25/03/2024  14:30            30,647 cake2.svg
25/03/2024  14:30               736 happy1.svg
25/03/2024  14:30            20,878 penguin1.svg
25/03/2024  14:30            20,956 penguin2.svg
              11 File(s)        126,217 bytes

 Directory of ...\converted\sounds

25/03/2024  14:30           538,172 happy_birthday.wav
               1 File(s)        538,172 bytes

When I tried to run the Python code, I got this error:
  File "...\converted\greeting_card.py", line 10
    self.play_sound_until_done("happy_birthday")penguin1 = stage.add_a_sprite(None)

I could see that there was missing a new-line between "happy_birthday") and penguin1
so I inserted a new-line and retried.

I encountered several more of these, but when finally all corrected, I got this error:
New costume: backdrop1 -> images/backdrop1.svg
New costume: backdrop2 -> images/backdrop2.svg
New costume: backdrop3 -> images/backdrop3.svg
Traceback (most recent call last):
  File "...\converted\greeting_card.py", line 9, in <module>
    self.when_backdrop_switches_to("backdrop3")
NameError: name 'self' is not defined

I could not debug further, so I raised this issue.
Please let me know if I have made any mistakes in trying to convert this project, or in my diagnosis, so far?

**Comment by kaiec** [comment]
Hey there, thanks for checking out PyStage and sorry for the late response, I had to take a break from development.

Your project converts well with the most recent version (0.1.0, released today). Here is the conversion result in the web converter: https://convert.pystage.org/conversion/JabZV-QKsX7

The converter reports a missing block: Looks -> Change effect by, so this will not yet fully work. I put it on the list of missing blocks (I think we have already a pull request that might address it, #59).

**Comment by kaiec** [comment]
This should be fixed by #59, please report back if it does not work.
