### ISSUE TITLE
Object conversion errors

### ISSUE THREAD

**Issue by DaikoGames** [pystage/pystage#113]
I made a Fangame called FlappyBirdBetter, it shouldn´t be online, but I found out that Objects were not converted correctly. Some Objects had bigger hitboxes, some were not even converted, and some were just converted but not shown, or the were not shown really. @kaiec, I am going to send it to you on Discord. 
The Conversion failed and sometimes objects were faster than they should be. 
A solution to the Object conversion could be that Pystage could get the (.sprite3) Files out of the Projects ant convert them into PNG format (For transparency effects) without any trouble and then get the Codes from The Scratch Blocks and convert it to Python. If it already functions like that, then the conversion should be changed or made better.

**Comment by kaiec** [comment]
I can't debug whole projects, please submit a minimal Scratch project that demonstrates the problem. SVG files are usually supported, NanoSVG is used: https://github.com/memononen/nanosvg 

NanoSVG has some limitations so it is to be expected that sometimes images do not look correct.

Automatic conversion beyond NanoSVG is not easy, we tried this in the past. A converter would need the proper license and has to work cross-platform, so far none of the available ones worked good enough. 

It is much easier and more reliable to have the users do the conversion themselves, so, yes, if you want maximum quality, you have to convert the files yourself. Inkscape is the recommended weapon of choice or some other graphics program (which obviously can't just be included in PyStage as another dependency). The recommended file format for images in PyStage is png.

**Comment by DaikoGames** [comment]
Is there no converter from SVG to PNG? Maybe this is the problem:
Maybe you could use the SVG format to png Format with this converter: https://github.com/oslllo/svg2?tab=readme-ov-file
Also it can be used for multiple picture formats, which can be used if the SVG is not good enough, also you could use this tool for upgrading our system if you learn how to work with it. It may be awkward and very bad, but it could be possible. Or is it too complicated?

**Comment by kaiec** [comment]
Closing this as not reproducible and/or resolved as not something that can be fixed in PyStage.
