### ISSUE TITLE
Stop All Block is missing

### ISSUE THREAD

**Issue by DaikoGames** [pystage/pystage#119]
Hey, I found out that the Block: "Stopp All" is missing. Could you please add it, so when a programm has this Block it just stops when there is the "Stop All" Block. In this example programm the character says something and then it should stop, there is just the Character, but it doesn´t even says something. So therer is not one Block missing, but i would appreciate it if the "Stopp All" Block would be implemented. Thanks in advance. 

Here is the Project: http://convert.pystage.org/conversion/dqYJ7-7Wb7g. The Sprite is from Turbowarp and not from me. I will delete the link after the problem is solved.

**Comment by kaiec** [comment]
The bug is most likely somewhere else, the stop all block is implemented, but my guess is it does not wait for the say block to be finished, based on your description. I'll check it.

**Comment by DaikoGames** [comment]
The Block stopp all isn´t really mentioned in the docs of Pystage. Or am I wrong?

**Comment by kaiec** [comment]
It is, however, as most of PyStage, only with a stub documentation string, documentation is working in principle, but does not have highest priority until the API is fully finished and stable.

https://github.com/pystage/pystage/blob/886f8858531aae03d3c7891632e0b9214df13609/src/pystage/de/sprite.py#L81

**Comment by kaiec** [comment]
```py
def when_program_starts_1(self):
    self.say_for_seconds("This Programm has a bug", 2.0)
    self.stop_all()
    self.say_for_seconds("This never shows", 2.0)
```

Modified example, the second text shows, but should not show. Further investigation needed.
