### ISSUE TITLE
AttributeError:'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by yuri0608** [pystage/pystage#18]
I use Python 3 version.  This error has any solution? Thanks

**Comment by whmsft** [comment]
can you provide the full error message?

**Comment by yuri0608** [comment]
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8728/3015968055.py in <module>
     33 primary_school_students_who_write_4663842.looks_goforwardbackwardlayers_forward(2)
     34 primary_school_students_who_write_4663842.looks_setsizeto(40)
---> 35 primary_school_students_who_write_4663842.looks_hide()
     36 primary_school_students_who_write_4663842.pystage_addcostume('easy', center_x=360, center_y=360, factor=2)
     37 primary_school_students_who_write_4663842.pystage_addcostume('fight', center_x=395.5, center_y=360, factor=2)

~\anaconda3\lib\site-packages\pystage\core\_looks.py in looks_hide(self)
    226 
    227     def looks_hide(self):
--> 228         print ("Hide", self)
    229         if not self.visible:
    230             return

~\anaconda3\lib\site-packages\pystage\core\sprite.py in __str__(self)
     38 
     39     def __str__(self):
---> 40         return self.costume_manager.get_costume().name

AttributeError: 'NoneType' object has no attribute 'name'

here is full error message. thanks for help

**Comment by whmsft** [comment]
I don't seem to reproduce the error, maybe share the entire source code?

**Comment by yuri0608** [comment]
# %load word_shooter.py
# word_shooter (pyStage, converted from Scratch 3)

from pystage.core import CoreSprite, CoreStage

stage = CoreStage()
stage.pystage_addbackdrop('room_1')
stage.pystage_addbackdrop('4d9255df71773f2d80dbdce634aedbad')
stage.pystage_addbackdrop('night_city')
stage.pystage_addbackdrop('galaxy')
stage.pystage_addbackdrop('stars')
stage.pystage_makevariable('抽到的')
stage.pystage_makevariable('字母編號')
stage.pystage_makevariable('分身編號')
stage.pystage_makevariable('造型編號')
stage.pystage_makevariable('回合結束')
stage.pystage_makevariable('單字題目')
stage.pystage_makevariable('關卡')
stage.pystage_makevariable('計時')
stage.pystage_makevariable('分數比較項次')
stage.pystage_makevariable('最終名次')
stage.pystage_makevariable('瞄準器存在')
stage.data_showvariable("單字題目")
stage.pystage_setmonitorposition("單字題目", -240, 157)
stage.data_showvariable("關卡")
stage.pystage_setmonitorposition("關卡", -240, 180)
stage.data_showvariable("計時")
stage.pystage_setmonitorposition("計時", -147, 180)
primary_school_students_who_write_4663842 = stage.pystage_createsprite(None)
primary_school_students_who_write_4663842.motion_setx(-181)
primary_school_students_who_write_4663842.motion_sety(-118.99999999999999)
primary_school_students_who_write_4663842.looks_gotofrontback_back()
primary_school_students_who_write_4663842.looks_goforwardbackwardlayers_forward(2)
primary_school_students_who_write_4663842.looks_setsizeto(40)
primary_school_students_who_write_4663842.looks_hide()
primary_school_students_who_write_4663842.pystage_addcostume('easy', center_x=360, center_y=360, factor=2)
primary_school_students_who_write_4663842.pystage_addcostume('fight', center_x=395.5, center_y=360, factor=2)
primary_school_students_who_write_4663842.looks_nextcostume()
primary_school_students_who_write_4663842.pystage_addsound('beat_your_competition')

def event_whenflagclicked_1(self):
    self.data_setvariableto("分身編號", "YES")
    self.data_setvariableto("關卡", "")
    self.data_setvariableto("分數比較項次", 1)
    self.data_setvariableto("計時", 0)
    self.looks_hide()
    "NO TRANSLATION: data_deletealloflist"
    "NO TRANSLATION: data_deletealloflist"
    "NO TRANSLATION: data_deletealloflist"
    self.data_setvariableto("單字題目", "")
    self.control_wait(4.0)
    self.data_setvariableto("分身編號", "YES")
    self.data_setvariableto("單字題目", "隨機產生中....")
    while not ("NO TRANSLATION: data_lengthoflist" == 5):
        self.data_setvariableto("抽到的", self.operator_random(1.0, 726.0))
        if not ("NO TRANSLATION: data_listcontainsitem"):
            "NO TRANSLATION: data_addtolist"
            "NO TRANSLATION: data_deletealloflist"
            self.data_setvariableto("字母編號", 1)
            "NO TRANSLATION: data_addtolist"
            while not (self.data_variable("字母編號") == len("NO TRANSLATION: data_itemoflist")):
                self.data_setvariableto("字母編號", (self.data_variable("字母編號") + 1.0))
                "NO TRANSLATION: data_addtolist"

            self.control_wait(5.0)
            self.data_setvariableto("抽到的", "NO TRANSLATION: data_itemoflist")
            self.data_changevariableby("關卡", 1.0)
            self.data_setvariableto("回合結束", 0)
            self.event_broadcast("產生字母")
            while not (self.data_variable("回合結束") == 1):
                pass

            self.data_setvariableto("抽到的", "".join(["正確答案: ", "NO TRANSLATION: data_itemoflist"]))
            self.data_setvariableto("瞄準器存在", "NO")
            "NO TRANSLATION: data_deletealloflist"

    self.data_setvariableto("關卡", "END")
    if (self.data_variable("計時") > "NO TRANSLATION: data_itemoflist"):
        "NO TRANSLATION: data_insertatlist"
        "NO TRANSLATION: data_insertatlist"
        self.data_setvariableto("最終名次", "NO TRANSLATION: data_lengthoflist")
    else:
        while not (self.data_variable("計時") < "NO TRANSLATION: data_itemoflist"):
            self.data_changevariableby("分數比較項次", 1.0)

        "NO TRANSLATION: data_insertatlist"
        "NO TRANSLATION: data_insertatlist"
        self.data_setvariableto("分數比較項次", self.data_variable("分數比較項次"))

    self.looks_show()
    if (self.data_variable("最終名次") < 11):
        self.looks_switchcostumeto("easy")
    else:
        self.looks_switchcostumeto("fight")

    self.looks_sayforsecs("遊戲結束", 1.0)
    self.looks_say("".join([self.sensing_username(), "".join([",你的名次是：第 ", "".join(["".join([self.data_variable("最終名次"), " 名，"]), "".join(["成績是： ", "".join([self.data_variable("計時"), " 秒"])])])])]))

primary_school_students_who_write_4663842.event_whenflagclicked(event_whenflagclicked_1)
letter = stage.pystage_createsprite(None)
letter.motion_setx(120)
letter.motion_sety(-129)
letter.looks_gotofrontback_back()
letter.looks_goforwardbackwardlayers_forward(1)
letter.motion_pointindirection(-171.46920215500197)
letter.looks_setsizeto(60)
letter.looks_hide()
letter.pystage_addcostume('a', center_x=36, center_y=37)
letter.pystage_addcostume('b', center_x=32, center_y=35)
letter.pystage_addcostume('c', center_x=27, center_y=35)
letter.pystage_addcostume('d', center_x=33, center_y=35)
letter.pystage_addcostume('e', center_x=34, center_y=38)
letter.pystage_addcostume('f', center_x=35, center_y=41)
letter.pystage_addcostume('g', center_x=32, center_y=39)
letter.pystage_addcostume('h', center_x=35, center_y=46)
letter.pystage_addcostume('i', center_x=21, center_y=38)
letter.pystage_addcostume('j', center_x=29, center_y=39)
letter.pystage_addcostume('k', center_x=38, center_y=36)
letter.pystage_addcostume('l', center_x=33, center_y=35)
letter.pystage_addcostume('m', center_x=42, center_y=39)
letter.pystage_addcostume('n', center_x=37, center_y=39)
letter.pystage_addcostume('o', center_x=29, center_y=39)
letter.pystage_addcostume('p', center_x=32, center_y=39)
letter.pystage_addcostume('q', center_x=33, center_y=43)
letter.pystage_addcostume('r', center_x=35, center_y=38)
letter.pystage_addcostume('s', center_x=27, center_y=40)
letter.pystage_addcostume('t', center_x=35, center_y=38)
letter.pystage_addcostume('u', center_x=37, center_y=37)
letter.pystage_addcostume('v', center_x=35, center_y=42)
letter.pystage_addcostume('w', center_x=45, center_y=41)
letter.pystage_addcostume('x', center_x=40, center_y=39)
letter.pystage_addcostume('y', center_x=38, center_y=41)
letter.pystage_addcostume('z', center_x=30, center_y=39)
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.looks_nextcostume()
letter.pystage_addsound('pop')
letter.pystage_makevariable('個別分身字母')

def control_start_as_clone_2(self):
    self.data_setvariableto("個別分身字母", self.sensing_of_costumename("NO TRANSLATION: sensing_of_object_menu"))
    self.looks_show()
    while True:
        self.motion_movesteps(2.0)
        self.motion_turnright(1.0)
        self.motion_ifonedgebounce()
        if (self.sensing_touchingobject_pointer() and (self.sensing_mousedown() and (self.data_variable("瞄準器存在") == "YES"))):
            if "NO TRANSLATION: data_listcontainsitem":
                "NO TRANSLATION: data_deleteoflist"

            self.control_delete_this_clone()

        if (self.data_variable("回合結束") == 1):
            self.control_delete_this_clone()

letter.control_start_as_clone(control_start_as_clone_2)

def event_whenbroadcastreceived_3(self):
    self.looks_hide()
    self.data_setvariableto("字母編號", 1)
    while not (self.data_variable("字母編號") == ("NO TRANSLATION: data_lengthoflist" + 1.0)):
        while not (self.looks_costumenumbername_name() == "NO TRANSLATION: data_itemoflist"):
            self.looks_nextcostume()

        self.data_changevariableby("字母編號", 1.0)
        self.motion_gotoxy(self.operator_random(-200.0, 200.0), self.operator_random(-150.0, 150.0))
        self.control_create_clone_of("NO TRANSLATION: control_create_clone_of_menu")

    self.data_setvariableto("瞄準器存在", "YES")
    while not (self.data_variable("字母編號") == 11):
        self.looks_nextcostume()
        self.data_changevariableby("字母編號", 1.0)
        self.motion_gotoxy(self.operator_random(-200.0, 200.0), self.operator_random(-150.0, 150.0))
        self.control_create_clone_of("NO TRANSLATION: control_create_clone_of_menu")

letter.event_whenbroadcastreceived("產生字母", event_whenbroadcastreceived_3)
images = stage.pystage_createsprite(None)
images.motion_setx(-180)
images.motion_sety(180)
images.looks_gotofrontback_back()
images.looks_goforwardbackwardlayers_forward(4)
images.pystage_addcostume('_2', center_x=47.5, center_y=46.5)
images.pystage_addsound('empyrean_electronic_rock_orchestral_soundtrack_hybrid_1_')
images.pystage_addsound('qiang_sheng')
images.pystage_addsound('xenogenesis_tasty_release')
images.pystage_addsound('pew')
images.pystage_addsound('beat_your_competition')

def event_whenthisspriteclicked_4(self):
    self.sound_playuntildone("pew")

images.event_whenthisspriteclicked(event_whenthisspriteclicked_4)

def event_whenflagclicked_5(self):
    self.data_setvariableto("瞄準器存在", "NO")
    self.control_wait(4.0)
    self.sensing_resettimer()
    while True:
        self.motion_goto_pointer()
        self.looks_gotofrontback_front()
        if ("NO TRANSLATION: data_lengthoflist" == 0):
            self.data_setvariableto("回合結束", 1)

        if (self.data_variable("瞄準器存在") == "NO"):
            self.looks_hide()
        else:
            self.looks_show()

        if (self.data_variable("關卡") == "END"):
            self.looks_hide()

        if (self.data_variable("關卡") < 6):
            self.data_setvariableto("計時", self.sensing_timer())

images.event_whenflagclicked(event_whenflagclicked_5)
info = stage.pystage_createsprite(None)
info.motion_setx(84)
info.motion_sety(90)
info.looks_gotofrontback_back()
info.looks_goforwardbackwardlayers_forward(3)
info.looks_hide()
info.pystage_addcostume('costume1', center_x=189.8472675, center_y=144.9218625)
info.pystage_addcostume('costume2', center_x=172.16290283203125, center_y=99.34879302978516)
info.looks_nextcostume()
info.pystage_addsound('pop')
info.pystage_addsound('beat_your_competition')

def event_whenflagclicked_6(self):
    self.motion_gotoxy(0.0, 0.0)
    self.looks_switchbackdropto("galaxy")
    self.looks_show()
    self.looks_switchcostumeto("costume1")
    self.control_wait(4.0)
    self.looks_hide()
    self.looks_switchbackdropto("4d9255df71773f2d80dbdce634aedbad")
    self.sound_play("beat_your_competition")
    while True:
        if (self.data_variable("關卡") == "END"):
            self.motion_gotoxy(84.0, 90.0)
            self.looks_show()
            self.looks_switchbackdropto("stars")
            self.looks_switchcostumeto("costume2")
            self.sound_stopallsounds()
        else:
            self.looks_hide()

info.event_whenflagclicked(event_whenflagclicked_6)

stage.pystage_play()

**Comment by kaiec** [comment]
Hi @whmsft , @yuri0608 , welcome to PyStage! It is great to see someone using our early stage prototype. Please feel free to join our Discord server if you want to get in touch or involved further (link is on website and GitHub).

Regarding the error here: The Sprite `primary_school_students_who_write_4663842` is created without Costume (Parameter `None` in the line where it is created). This leads to the error as the costume is part of the String output. This is probably a mistake of the converter, or did you change this line yourself? A Sprite without costume is probably not a good idea, either. Is this possible in Scratch? This might be the core of the problem.

In any case, we should make PyStage more robust here, so thanks for pointing this out, I will fix it soon, but need to understand better first, what the behaviour of Scratch is in this case.

**Comment by kaiec** [comment]
This got fixed in commit 9e6b2a17d5b3e57a2e7dabbbec76af7d940dd033. A sprite without costume is not supported in Scratch. You can force this in PyStage by setting costume to None, as the converter does, but as long as a costume is set when the actual execution begins, this is now not a problem anymore.
