### ISSUE TITLE
Error while finding module specification for 'pystage.convert.sb3' (ModuleNotFoundError: No module named 'pystage')

### ISSUE THREAD

**Issue by MinecrasfsftMan** [pystage/pystage#26]
I haven't used Python in 5 months, but I need help on how to fix this.

I'm bad at explaining so here's an image of the error:
![eror](https://user-images.githubusercontent.com/71991306/183102231-734c46f9-e9c8-468e-8a3f-8d350f1b7173.png)

**Comment by VictorNorman** [comment]
When you do the conversion, you need to be in the `src` directory of the `pystage` installation.  E.g., I did a git clone to pull down all the source code for `pystage` and I put it in my `/Users/vtn2/src/pystage directory`.

To run a conversion I cd to `/Users/vtn2/src/pystage/src` and then run

`python3 -m pystage.convert.sb3 blah blah etc...`

The `-m pystage.convert.sb3` tells python to look in the ./python/convert/ directory for the sb3.py file and run that. 

hope this helps.

**Comment by kaiec** [comment]
Is pystage actually installed? `pip install pystage` is the easiest way.

**Comment by MinecrasfsftMan** [comment]
> Is pystage actually installed? `pip install pystage` is the easiest way.

I should've noted this before publishing it. Yes, it's already installed.

**Comment by MinecrasfsftMan** [comment]
> When you do the conversion, you need to be in the `src` directory of the `pystage` installation.

I tried this method, but it didn't work.

**Comment by kaiec** [comment]
Your folder names indicate that you might have two versions of Python installed. 3.7 and 3.9 Make sure that the one you are executing is the one where pystage is installed.

**Comment by MinecrasfsftMan** [comment]
> Your folder names indicate that you might have two versions of Python installed. 3.7 and 3.9 Make sure that the one you are executing is the one where pystage is installed.

I think you are right! But, idk how to uninstall programs on python.

**Comment by MinecrasfsftMan** [comment]
Because I can't reinstall an app into a different directory, I had to copy some of the files to Python 3.9

But when I did that, it gave me this message
![error2](https://user-images.githubusercontent.com/71991306/183256206-0263f6e3-61a5-467f-942e-c81d778ec98d.png)
:

**Comment by MinecrasfsftMan** [comment]
Ok, I put every library into Python 3.9, but it says this now
![error3](https://user-images.githubusercontent.com/71991306/183261141-f89c0569-755d-4de2-a903-cd1e9a028993.png)
:

**Comment by kaiec** [comment]
These are all dependencies of Pystage. You have to find out how to use pip to install modules for the Python version you use. This has nothing to do with Pystage, sorry.

**Comment by MinecrasfsftMan** [comment]
> These are all dependencies of Pystage. You have to find out how to use pip to install modules for the Python version you use. This has nothing to do with Pystage, sorry.

I just realized that. I will close this until further notice.
