### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by MinecrasfsftMan** [pystage/pystage#27]
I think this might be the game I chose, but it's still something to look forward to fixing
![anothererrorbuthey](https://user-images.githubusercontent.com/71991306/183271115-d2f06763-f506-406a-8649-05a5ea9f503d.png)
.

**Comment by kaiec** [comment]
Please always paste your source code (or relevant part) and a link to the Scratch project when you use the converter.

**Comment by MinecrasfsftMan** [comment]
> Please always paste your source code (or relevant part) and a link to the Scratch project when you use the converter.

what source code? And where do I add the link to the Scratch Project?

**Comment by MinecrasfsftMan** [comment]
I think my game was a bit too complex to convert my project correctly. Turns out, it's true. I chose a less complex game to convert, and it works (almost) perfectly!

**Comment by kaiec** [comment]
> > Please always paste your source code (or relevant part) and a link to the Scratch project when you use the converter.
> 
> what source code? And where do I add the link to the Scratch Project?

The source code you run, so either your own python code or the result of the conversion. 

You can simply share your scratch project publicly and just post a link to your project here.

Great that it works now. Keep in mind that Pystage is still early development, many blocks from Scratch are just not yet implemented.
