### ISSUE TITLE
Variable syntax is not recognized

### ISSUE THREAD

**Issue by jadasse** [pystage/pystage#28]
When I converted the sb3 of https://turbowarp.org/635074434 to python, pystage gives me this error:

File "wth.py", line 300
    33.set_name("33")
      ^
SyntaxError: invalid decimal literal

Is there an incompatibility with variables and syntaxes?

**Comment by kaiec** [comment]
Hi @jadasse, thanks for the report. Could you share the project on Scratch so that I can look into it and run the converter myself? From you code snippet, it looks like there is a problem with our converter, as Scratch seems to allow numbers as variable names which are of course not allowed in Python. I will check the respective code,  we have to make sure that only valid Python variable names are created.

**Comment by kaiec** [comment]
@jadasse I fixed the problem in the converter, please try the new version 0.0.16. It should help. If not, please answer here with the link to the project.

**Comment by jadasse** [comment]
New costume: backdrop1 -> images/backdrop1.svg
New code block registered: when_i_receive_1-0
Bound to broadcast message 'ntsctopal': when_i_receive_1-0
New code block registered: when_i_receive_2-1
Bound to broadcast message 'paltontsc': when_i_receive_2-1
New code block registered: when_i_receive_3-2
Bound to broadcast message '33to45': when_i_receive_3-2
New code block registered: when_i_receive_4-3
Bound to broadcast message '45to78': when_i_receive_4-3
New code block registered: when_i_receive_5-4
Bound to broadcast message '33to78': when_i_receive_5-4
New code block registered: when_i_receive_6-5
Bound to broadcast message '45to33': when_i_receive_6-5
New code block registered: when_i_receive_7-6
Bound to broadcast message '78to33': when_i_receive_7-6
New code block registered: when_i_receive_8-7
Bound to broadcast message '78to45': when_i_receive_8-7
New code block registered: when_i_receive_9-8
Bound to broadcast message 'reset': when_i_receive_9-8
New code block registered: when_key_pressed_10-9
Traceback (most recent call last):
  File "C:\Users\dlada\Documents\scratch\wth_1\wth.py", line 79, in <module>
    stage.when_key_pressed("left arrow", when_key_pressed_10)
  File "C:\Users\dlada\AppData\Roaming\Python\Python310\site-packages\pystage\en\stage.py", line 365, in when_key_pressed
    return self._core.event_whenkeypressed(key, generator_function, name, no_refresh)
  File "C:\Users\dlada\AppData\Roaming\Python\Python310\site-packages\pystage\core\_events.py", line 26, in event_whenkeypressed
    raise ValueError(f"Bad key: {key}. Only a-z, 0-9 and space are allowed.")
ValueError: Bad key: left arrow. Only a-z, 0-9 and space are allowed.

Still crashed on me; this is the project I am converting: https://turbowarp.org/635074434

**Comment by kaiec** [comment]
Please share the project on Scratch, I can't see the code on turbowarp. Alternatively upload the sb3 file here.
