### ISSUE TITLE
Sensing touching does not have a API for converting

### ISSUE THREAD

**Issue by coreknee** [pystage/pystage#29]
![image](https://user-images.githubusercontent.com/89991965/202797752-39742801-cb14-4b87-aec8-7fe2d23d5d2d.png)

**Comment by coreknee** [comment]
Windows 10

**Comment by coreknee** [comment]
oh also i cant manually try to code the sensing in cause it keeps saying that floor isnt defined (floor is the sprite that im trying to test sensing with) also my code is here after i manually coded it 

<details>
<summary>python code</summary>

`
testingproject (pyStage, converted from Scratch 3)

from pystage.en import Sprite, Stage

stage = Stage()
stage.add_backdrop('backdrop1')
stage.create_variable('my variable')
stage.create_variable('speedy')
stage.create_variable('speedx')
stage.create_variable('lock')
stage.show_variable("speedx")
stage.set_monitor_position("speedx", -235, 148)
stage.show_variable("speedy")
stage.set_monitor_position("speedy", -235, 121)
sprite1 = stage.add_a_sprite(None)
sprite1.set_name("Sprite1")
sprite1.set_x(0)
sprite1.set_y(0)
sprite1.go_to_back_layer()
sprite1.go_forward(2)
sprite1.add_costume('costume1', center_x=95, center_y=99, factor=2)
sprite1.add_costume('costume2', center_x=91, center_y=105, factor=2)
sprite1.add_sound('meow')
sprite1.create_variable('TouchingWall?')

def when_program_starts_1(self):
    self.set_variable("speedy", 0)
    self.set_variable("speedx", 0)
    self.go_to_x_y(0.0, 0.0)
    while True:
        if self.key_pressed("a"):
            self.change_variable_by("speedx", -1.0)

        if self.key_pressed("d"):
            self.change_variable_by("speedx", 1.0)

        if self.key_pressed("w"):
            if (self.get_variable("lock") == 0):
                self.set_variable("speedy", 10)
                self.set_variable("lock", 1)

        if self.touching(floor):
            self.set_variable("TouchingWall?", "true")
        else:
            self.set_variable("TouchingWall?", "false")

        if ((self.get_variable("TouchingWall?") == "true") or (self.get_variable("TouchingWall?") == 1)):
            self.change_x_by((self.get_variable("speedx") * -1.0))
            self.set_variable("speedx", 0)
        else:
            self.change_x_by(self.get_variable("speedx"))
            self.set_variable("speedx", (self.get_variable("speedx") * 0.8))

        self.change_y_by(self.get_variable("speedy"))
        if self.touching(floor):
            self.set_variable("TouchingWall?", "true")
        else:
            self.set_variable("TouchingWall?", "false")

        if ((self.get_variable("TouchingWall?") == "true") or (self.get_variable("TouchingWall?") == 1)):
            self.change_y_by((self.get_variable("speedy") * -1.0))
            self.set_variable("speedy", 0)
            self.set_variable("lock", 0)
        else:
            self.change_variable_by("speedy", -1.0)
            self.set_variable("lock", 1)
sprite1.when_program_starts(when_program_starts_1)
floor = stage.add_a_sprite(None)
floor.set_name("Floor")
floor.set_x(0)
floor.set_y(0)
floor.go_to_back_layer()
floor.go_forward(1)
floor.add_costume('costume1_2', center_x=480, center_y=360, factor=2)
floor.add_sound('pop')
stage.play()
`
</details>

**Comment by kaiec** [comment]
The block is implemented in 4b70cce020332acfde9d24ce30ea34f244369aa5 and should work. It would be great if you could test this with your project.
