### ISSUE TITLE
Clones missing

### ISSUE THREAD

**Issue by Aslanpel** [pystage/pystage#30]
i try to create clones and they dont appear

**Comment by kaiec** [comment]
Unfortunately Clones are not yes implemented. For reference here is the relevant location in the code:

https://github.com/pystage/pystage/blob/fb015aadba127716970c63c27d213f19f211591b/src/pystage/core/_control.py#L33

Clones probably require some thought to do them right, therefore I can't promise a quick implementation. But I will put it on my list. If someone wants to chime in, please use this issue to coordinate this. Maybe it is easier than I think.

**Comment by kaiec** [comment]
This is actually a duplicate of #24, I try to prioritize it.

**Comment by Aslanpel** [comment]
when do you gonna fix the issue?

**Comment by kaiec** [comment]
Hopefully soon... sorry, I can't promise anything or make better predictions right now.

**Comment by kaiec** [comment]
Clones should work now, if possible please test it. To test a feature that is not yet released, download PyStage from GitHub as Zip-File (make sure to switch to the correct branch first, in this case "clones"). The Zip-File contains a src Folder, in the src Folder is the pystage Folder. This pystage-Folder needs to be extracted and copied into the same directory, where your Python-Script is.
