### ISSUE TITLE
Conversion script generates: NO API method for func.opcode incorrectly.

### ISSUE THREAD

**Issue by loyaniu** [pystage/pystage#33]
Examples:
If the scratch block is "motion_goto", there are two choices: _random_, and _mouse_, when converter trying to convert this, it generates "NO API method for motion_goto_menu"

If the scratch block is "motion_glideto", there are two choices: _random_, and _mouse_, when converter trying to convert this, it generates 
"NO API method for motion_glideto_menu"

This error message comes out here: https://github.com/pystage/pystage/blob/main/src/pystage/convert/code_writer.py#LL141C12-L141C12

**Comment by kaiec** [comment]
I tested it, this seems to be fixed now.
