### ISSUE TITLE
repeat block with no contents generates bad output

### ISSUE THREAD

**Issue by VictorNorman** [pystage/pystage#34]
Build a scratch project that is just:

when this sprite clicked:
    repeat 10
         <nothing here>

The output from conversion is:
```
... snip ...
def when_this_sprite_clicked_1(self):
    for _ in range({{TIMES}}):
        {{SUBSTACK | indent(4)}}


sprite1.when_this_sprite_clicked(when_this_sprite_clicked_1)

stage.play()
```

The odd thing is that if you put something in the substack, then it says 10 instead of TIMES in the for loop.

So, there may be multiple issues here, actually.

**Comment by kaiec** [comment]
I tested this, this seems to be fixed now.
