### ISSUE TITLE
uninitialized if block generates bad output 

### ISSUE THREAD

**Issue by VictorNorman** [pystage/pystage#35]
Create a project that jsut has:

when this sprite clicked:
    if    <initialized condition> then
        <nothign ehre>

Output is:

```
... snip ...
def when_this_sprite_clicked_1(self):
    if {{CONDITION}}:
        {{SUBSTACK | indent(4)}}
```

Similar to issue #34

**Comment by kaiec** [comment]
I tested this, this seems to be fixed now.
