### ISSUE TITLE
Some nested blocks of  ___ of __ block, e.g. tan of 90 not work well.

### ISSUE THREAD

**Issue by loyaniu** [pystage/pystage#38]
https://github.com/pystage/pystage/blob/main/src/pystage/core/_operators.py

Tan and log operators were not implemented correctly.

And when a sprite say a calculated result, an error occured because of type(Should convert integer or float to string).

And some calculated values are not consistent with values get from Scratch, like "NaN", "Infinity", and "-Infinity".

**Comment by kaiec** [comment]
This is fixed with PR #58
