### ISSUE TITLE
I cant load pystage

### ISSUE THREAD

**Issue by Melvovin** [pystage/pystage#42]
I cant load pystage the readme file dont help me.

**Comment by loyaniu** [comment]
Please try these commands one by one before pip install pystage:

```bash
pip install wheel
pip install pygame==2.3.0
pip install svglib==1.1.0
pip install reportlab==3.5.67
pip install pystage
```

**Comment by kaiec** [comment]
IIRC you added the information already in the README.md, @Zhonglin-Niu . We can close this once the pull request is created and merged.

**Comment by loyaniu** [comment]
> 

Yes

**Comment by Melvovin** [comment]
I executed the commands :
pip install wheel
pip install pygame==2.3.0
pip install svglib==1.1.0
pip install reportlab==3.5.67
pip install pystage

and it says : note: This error originates from a subprocess, and is likely not a problem with pip

**Comment by kaiec** [comment]
Then it is likely not a problem with PyStage, neither :-) I will close this issue now, feel free to join our Discord and copy paste the full error message there, maybe someone can help.
