### ISSUE TITLE
Sound Problem

### ISSUE THREAD

**Issue by OftenUser** [pystage/pystage#91]
I've tried everything to get a freakin' sound to play into my program, even reading the docs, but THERE'S NO ACTUAL EXPLANATION, can you PLEASE just show an image or a GIF of it's actual use? It's so hard...

Literally, it just says "play_sound_until_done(name)" but I'm doing that and it's not working

And no, I'm not using an mp3, I tried using a wav, didn't work, and an ogg currently, DOESN'T WORK

**Comment by OftenUser** [comment]
I even tried changing the file extension to all of them possible and it still never works unless I just "DON'T" use the sound.

**Comment by OftenUser** [comment]
Here's all of the code if you need all the explanations:

<pre>
import pystage
from pystage.en import Sprite, Stage
from pystage import core

stage = Stage()
stage.add_backdrop('oftenguybackground')

oftenguy = stage.add_a_sprite(None)
oftenguy.add_costume('oftenguy')
oftenguy.set_size_to(0.0)
oftenguy.set_ghost_effect_to(0)
oftenguy.go_to_x_y(0.0, 0.0)
# oftenguy_theme = oftenguy.add_sound('oftenguytheme')
# oftenguy.add_sound(oftenguy, 'oftenguytheme')

def intro1(self):
    for _ in range(20):
        self.change_size_by(2.5)
    self.wait(2)
    for _ in range(10):
        self.change_size_by(-5)

def intro2(self):
    for _ in range(20):
        self.change_ghost_effect_by(-2.5)
    self.wait(2)
    for _ in range(10):
        self.change_ghost_effect_by(5)

def intro3(self):
    oftenguy_theme = self.add_sound("oftenguytheme")
    self.play_sound_until_done(oftenguy_theme)

oftenguy.when_program_starts(intro1, no_refresh=False)
oftenguy.when_program_starts(intro2, no_refresh=False)
oftenguy.when_program_starts(intro3, no_refresh=False)

stage.play()
</pre>

**Comment by OftenUser** [comment]
It's the intro3 part that is the issue

**Comment by OftenUser** [comment]
I was just trying to remake my upcoming game in Python, was working on the intro part, and now I'm forever stuck unless someone just HELPS ME

**Comment by loyaniu** [comment]
Changed code:

```python
def intro3(self):
    self.add_sound("oftenguytheme")
    self.play_sound_until_done("oftenguytheme")
```

**Comment by loyaniu** [comment]
`play_sound_until_done` method receives the name of sound, not a variable.

**Comment by OftenUser** [comment]
Oh, really?

I thought that's what I had been doing all along...

Thanks, it worked!

**Comment by OftenUser** [comment]
Now I can finally close this down now that everyone can find out about this if they need help!
